export const theme = {
  colors: {
    surface: '#f7f9fc',
    surfaceDim: '#d8dadd',
    surfaceBright: '#f7f9fc',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f2f4f7',
    surfaceContainer: '#eceef1',
    surfaceContainerHigh: '#e6e8eb',
    surfaceContainerHighest: '#e0e3e6',
    onSurface: '#191c1e',
    onSurfaceVariant: '#424752',
    inverseSurface: '#2d3133',
    inverseOnSurface: '#eff1f4',
    outline: '#727783',
    outlineVariant: '#c2c6d4',
    surfaceTint: '#005db7',
    primary: '#004d99',
    onPrimary: '#ffffff',
    primaryContainer: '#1565c0',
    onPrimaryContainer: '#dae5ff',
    inversePrimary: '#a9c7ff',
    primaryFixed: '#d6e3ff',
    onPrimaryFixed: '#001b3d',
    onPrimaryFixedVariant: '#00468c',
    primaryFixedDim: '#a9c7ff',
    secondary: '#515d84',
    onSecondary: '#ffffff',
    secondaryContainer: '#c4d0fd',
    onSecondaryContainer: '#4c587f',
    tertiary: '#005281',
    onTertiary: '#ffffff',
    tertiaryContainer: '#006ba6',
    onTertiaryContainer: '#d2e7ff',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
  },
  typography: {
    displayLg: { fontFamily: 'Roboto Flex', fontSize: 57, fontWeight: '400', lineHeight: 64 },
    displayMd: { fontFamily: 'Roboto Flex', fontSize: 45, fontWeight: '400', lineHeight: 52 },
    displaySm: { fontFamily: 'Roboto Flex', fontSize: 36, fontWeight: '400', lineHeight: 44 },
    headlineLg: { fontFamily: 'Roboto Flex', fontSize: 32, fontWeight: '600', lineHeight: 40 },
    headlineMd: { fontFamily: 'Roboto Flex', fontSize: 28, fontWeight: '600', lineHeight: 36 },
    headlineSm: { fontFamily: 'Roboto Flex', fontSize: 24, fontWeight: '600', lineHeight: 32 },
    titleLg: { fontFamily: 'Roboto Flex', fontSize: 22, fontWeight: '500', lineHeight: 28 },
    titleMd: { fontFamily: 'Roboto Flex', fontSize: 16, fontWeight: '600', lineHeight: 24 },
    titleSm: { fontFamily: 'Roboto Flex', fontSize: 14, fontWeight: '600', lineHeight: 20 },
    bodyLg: { fontFamily: 'Roboto Flex', fontSize: 16, fontWeight: '400', lineHeight: 24 },
    bodyMd: { fontFamily: 'Roboto Flex', fontSize: 14, fontWeight: '400', lineHeight: 20 },
    bodySm: { fontFamily: 'Roboto Flex', fontSize: 12, fontWeight: '400', lineHeight: 16 },
    labelLg: { fontFamily: 'Roboto Flex', fontSize: 14, fontWeight: '500', lineHeight: 20 },
    labelMd: { fontFamily: 'Roboto Flex', fontSize: 12, fontWeight: '500', lineHeight: 16 },
    labelSm: { fontFamily: 'Roboto Flex', fontSize: 11, fontWeight: '500', lineHeight: 16 },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  rounded: {
    sm: 4,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  }
};
